name: Releaser

on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "**/go.mod"
      - "**/go.sum"
  workflow_dispatch: {}

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WITH_V: true
          DRY_RUN: true
      - run: |
          tee version.go << END
          package aiven

          // Version returns aiven-go-client version string
          func Version() string {
                  return "${{ steps.version.outputs.new_tag }}"
          }
          END
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore(version.go): update aiven-go-client version"
          git push
      - id: sha
        run: |
          GIT_SHA=$(git rev-parse HEAD)
          echo "sha=${GIT_SHA::7}" >> $GITHUB_OUTPUT
      - id: tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WITH_V: true
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.new_tag }}
          name: ${{ steps.version.outputs.new_tag }}
          body: auto-generated release for commit ${{ steps.sha.outputs.sha }}
